config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  devise_for :users, controllers: { passwords: 'devise/passwords' }
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] 
      resources :likes, only: [:create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  after_create :update_user_posts_counter

  def update_user_posts_counter
    update(posts_counter: posts.count)
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def last_posts
    posts.order(created_at: :desc).limit(5)
  end

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= 'user'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id]) || not_found
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<main>
  <section>
  <h1 class="createTitle">Blogify Users</h1>
    <ul class="card-container">
      <% @users.each do |user| %>
        <%= link_to user do %>
          <li class="postCont">
            <div class="usersCont">
              <div class="photo-container">
                <%if user.photo.present? %>
                  <%= image_tag user.photo, class: "user-photo" %>
                <% else %>

                <% end %>
              </div>
              <div class="user-information">
                <h2><%= user.name %></h2>
                <p>Number of posts: <%= user.posts_counter || 0 %></p>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section class="card">
  <div class="userContainer"> 
    <div class="photo-container">
      <%if @user.photo.present? %>
        <%= image_tag @user.photo, class: "user-photo" %>
      <% else %>

      <% end %>
    </div>
    <div class="user-information">
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  </section>

  <section class="biography">
    <h2>Biography</h2>
    <p><%= @user.bio %></p>
  </section>

  <section>
    <ul>
      <% @user.last_posts.each do |post| %>
        <li class="postCont">
          <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
            <h3 class="contTitle"><%= post.title %></h3>
            <h4 class="contText"><%= post.text %></h4>
            <div class="postCounters">
              <p>Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></p>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="btn-container"> 
      <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
    </div>
  </section> 
</main>