config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  devise_for :users, controllers: { passwords: 'devise/passwords' }
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] 
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter
  after_create :initialize_comments_counter
  before_validation :set_default_counters

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def initialize_comments_counter
    update(comments_counter: 0, likes_counter: 0)
  end

  def set_default_counters
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = User.find(params['user_id']).posts

    render json: posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  before_action :set_user, only: %i[new create]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = @user.posts.new
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    author = @post.author
    author.decrement!(:posts_counter)
    @post.destroy!
    redirect_to user_posts_path(id: author.id), notice: 'Post deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<main>
  <div class="card">
    <h1><%= @user.name %></h1>
    <h3>Number of posts: <%= @user.posts_counter %></h3>
  </div>
  <div>
    <div class="btn-container">
       <% if @user == current_user %>
          <%= link_to "Create a post", new_user_post_path(@user), class: "btn" %>
       <% end %>
    </div>
    <ul>
      <% @posts.includes(:author, :comments, comments: :author).each do |post| %>
        <%= link_to user_post_path(user_id: post.author.id, id: post.id) do %>
          <div class="postContainer">
            <li class="postCont">
              <div class="post"> 
                <h2 class="postTitle"><%= post.title %></h2>
                <h4 class="postText"><%= post.text %></h4>
                <div class="postCounters">
                  <p class="countText"> Comments: <%= post.comments_counter %> - Likes: <%= post.likes_counter %></p>
                </div>
              </div>
            </li>
            <div class="postCont">
              <h3>Comments:</h3>
              <ul>
                <% if post.comments.any? %>
                  <% post.comments.each do |comment| %>
                    <li>
                      <p class="commentText"><%= comment.author.name %> : <%= comment.text %></p>
                    </li>
                  <% end %>
                <% else %>
                  <li>
                    <p class="commentText">No comments yet.</p>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</main>

app/views/posts/new.html.erb
<main class="card">
  <h2 class="createTitle">Create a Post</h2>
  <section class="postContP">
    <%= form_with(model: @post, url: user_posts_path(@user), class:"formAdd") do |form| %>
      <%= form.label :title %>
      <%= form.text_field :title, required: true %>
      <%= form.label :text %>
      <%= form.text_area :text, required: true %>
      <%= form.submit 'Create Post', class: "btn" %>
    <% end %>
  </section>
</main>

app/views/posts/show.html.erb
<main>
  <section class="postCont">
    <div class="postContP">
      <div class="postP">
        <h3 class="postTitleP">
          Post Nº <%= @post.id %> by <%= @post.author.name %></h3>
        <div class="postCountersP">
          <p class="postText"> Comments: <%= @post.comments_counter %> - Likes: <%= @post.likes_counter %></p>
        </div>
      </div>
      <p class="contText"><%= @post.text %></p>
    </div>
    </div>

    <div class="postContP">
      <ul>
        <% @post.comments.includes(:author).includes(:post).each do |comment| %>
          <p class="contText"><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to "Delete Comment", user_post_comment_path(user_id: @post.author_id, post_id: @post.id, id: comment.id), method: :delete, class: "btn delete" %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="interaction">
      <div class="likeBtn">
        <div class="shareIt">
          <% if user_signed_in? %>
            <%= link_to 'Add a Comment', new_user_post_comment_path(@post.author, @post), class: "btn" %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <%= form_with(url: user_post_likes_path(@post.author, @post), method: :post) do |form| %>
            <%= form.submit 'Like', class: "btn" %>
          <% end %>
        <% end %>
      </div>
      <% if user_signed_in? && can?(:destroy, @post) %>
        <%= button_to 'Delete post', user_post_path(@post.author, @post), method: :delete, class: "btn delete" %>
      <% end %>
    </div>
  
  </section>
</main>